name: ajmancli
description: Internal code gen tool for Ajman bank project.
homepage: https://github.com/saffer4u/ajman_cli
repository: https://github.com/saffer4u/ajman_cli
version: 1.0.1
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
# path: ^1.8.0
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  ajmancli: ajmancli
# dart pub global activate --source path .
