name: ajmancli
description: A CLI tool for internal code generation in the Ajman Bank project, designed to streamline development and boost productivity.
homepage: https://github.com/saffer4u/ajman_cli
repository: https://github.com/saffer4u/ajman_cli
version: 1.0.3
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  path: ^1.9.1
  pubspec_parse: ^1.5.0
# path: ^1.8.0
dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0

executables:
  ajmancli: ajmancli
# dart pub global activate --source path .
